CREATE TABLE HUB_ORDER (
    ORDER_HK VARCHAR(32) PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    LOAD_DATE TIMESTAMP NOT NULL,
    RECORD_SOURCE VARCHAR(100) NOT NULL
) DISTRIBUTED BY (ORDER_HK);

CREATE TABLE HUB_PRODUCT (
    PRODUCT_HK VARCHAR(32) PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    LOAD_DATE TIMESTAMP NOT NULL,
    RECORD_SOURCE VARCHAR(100) NOT NULL
) DISTRIBUTED BY (PRODUCT_HK);

CREATE TABLE HUB_CUSTOMER (
    CUSTOMER_HK VARCHAR(32) PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    LOAD_DATE TIMESTAMP NOT NULL,
    RECORD_SOURCE VARCHAR(100) NOT NULL
) DISTRIBUTED BY (CUSTOMER_HK);

CREATE TABLE HUB_LOCATION (
    LOCATION_HK VARCHAR(32) PRIMARY KEY,
    POSTAL_CODE VARCHAR(20) NOT NULL,
    LOAD_DATE TIMESTAMP NOT NULL,
    RECORD_SOURCE VARCHAR(100) NOT NULL
) DISTRIBUTED BY (LOCATION_HK);
