CREATE TABLE LINK_ORDER_DETAILS (
    ORDER_DETAILS_HK VARCHAR(32) PRIMARY KEY,
    ORDER_HK VARCHAR(32) NOT NULL,
    PRODUCT_HK VARCHAR(32) NOT NULL,
    LOAD_DATE TIMESTAMP NOT NULL,
    RECORD_SOURCE VARCHAR(100) NOT NULL
) DISTRIBUTED BY (ORDER_DETAILS_HK);

CREATE TABLE LINK_CUSTOMER_ORDER (
    CUSTOMER_ORDER_HK VARCHAR(32) PRIMARY KEY,
    CUSTOMER_HK VARCHAR(32) NOT NULL,
    ORDER_HK VARCHAR(32) NOT NULL,
    LOAD_DATE TIMESTAMP NOT NULL,
    RECORD_SOURCE VARCHAR(100) NOT NULL
) DISTRIBUTED BY (CUSTOMER_ORDER_HK);

CREATE TABLE LINK_PRODUCT_LOCATION (
    PRODUCT_LOCATION_HK VARCHAR(32) PRIMARY KEY,
    PRODUCT_HK VARCHAR(32) NOT NULL,
    LOCATION_HK VARCHAR(32) NOT NULL,
    LOAD_DATE TIMESTAMP NOT NULL,
    RECORD_SOURCE VARCHAR(100) NOT NULL
) DISTRIBUTED BY (PRODUCT_LOCATION_HK);
