CREATE TABLE SAT_ORDER_DETAILS (
    ORDER_HK VARCHAR(32) NOT NULL,
    ORDER_DATE TIMESTAMP,
    SHIP_DATE TIMESTAMP,
    SHIP_MODE VARCHAR(50),
    LOAD_DATE TIMESTAMP NOT NULL,
    RECORD_SOURCE VARCHAR(100) NOT NULL,
    HASH_DIFF VARCHAR(32) NOT NULL,
    EFFECTIVE_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP,
    PRIMARY KEY (ORDER_HK, EFFECTIVE_DATE)
) DISTRIBUTED BY (ORDER_HK);

CREATE TABLE SAT_CUSTOMER_DETAILS (
    CUSTOMER_HK VARCHAR(32) NOT NULL,
    SEGMENT VARCHAR(50),
    LOAD_DATE TIMESTAMP NOT NULL,
    RECORD_SOURCE VARCHAR(100) NOT NULL,
    HASH_DIFF VARCHAR(32) NOT NULL,
    EFFECTIVE_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP,
    PRIMARY KEY (CUSTOMER_HK, EFFECTIVE_DATE)
) DISTRIBUTED BY (CUSTOMER_HK);

CREATE TABLE SAT_SALES_TRANSACTION (
    ORDER_HK VARCHAR(32) NOT NULL,
    PRODUCT_HK VARCHAR(32) NOT NULL,
    SALES DECIMAL(18,2),
    QUANTITY INTEGER,
    DISCOUNT DECIMAL(4,2),
    PROFIT DECIMAL(18,2),
    LOAD_DATE TIMESTAMP NOT NULL,
    RECORD_SOURCE VARCHAR(100) NOT NULL,
    HASH_DIFF VARCHAR(32) NOT NULL,
    EFFECTIVE_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP,
    PRIMARY KEY (ORDER_HK, PRODUCT_HK, EFFECTIVE_DATE)
) DISTRIBUTED BY (ORDER_HK);
